/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.conexionDB;
import Controlador.*;
import modelo.*;

/**
 *
 * @author Macao
 */
public class actualizarDatosEmpleado extends javax.swing.JFrame {

    
      Usuario user;
    ControlPersona controlPer ;
    conexionDB con = new conexionDB();
    int id;
    
    public actualizarDatosEmpleado(Usuario usuario) {
        initComponents();
        user = usuario;
        controlPer = new ControlPersona();
        setLocationRelativeTo(null);
        setTitle("Actualizar Datos de un Empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCedula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonActualizarDatos = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jTextCedula = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextConvencional = new javax.swing.JTextField();
        jTextCelular = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jTextContraseña = new javax.swing.JTextField();
        jTextCargo = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datos = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCedula.setForeground(new java.awt.Color(0, 0, 255));
        jLabelCedula.setText("Cedula:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Apellido:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Direccion:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Tel.Convencional");

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Tel.Celular");

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Usuario:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Contraseña");

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Cargo");

        jButtonActualizarDatos.setText("Actualizar Datos");
        jButtonActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarDatosActionPerformed(evt);
            }
        });

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar por Cedula");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar por Nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("E : empleado");

        jLabel10.setText("A : administrador");

        datos.setText("Datos de un:");

        info.setText("Info.");

        info2.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextConvencional, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonActualizarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRegresar)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCelular))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextApellido))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextContraseña))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(info2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGap(0, 42, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCedula)
                            .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar)
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(info2)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextConvencional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(datos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        VntMenuEmpleado ver = new VntMenuEmpleado(user);
        ver.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
         if(jTextCedula.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Campo Cedula Vacio", "Error de Campos", javax.swing.JOptionPane.WARNING_MESSAGE);
    
         }else{
            Usuario per = new Usuario();
        jTextNombre.setText("");
         con.Conectar();
        per = controlPer.buscarEmpleadoDatos(con, jTextCedula.getText(), jTextNombre.getText());
        con.CerrarConexion();
        System.out.println("datos : " + per);
             try {
                 id = per.getId();
                 if(per.getCargo().equalsIgnoreCase("C")){
        jTextCedula.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDireccion.setText("");
        jTextConvencional.setText("");
        jTextCelular.setText("");
        jTextCargo.setText("");
        jTextUsuario.setText("");
        jTextContraseña.setText("");
        info.setText("No se puede editar informacion");
        info2.setText("de un cliente en esta ventana");
            
        }else if(per.getCargo().equalsIgnoreCase("A")){
                datos.setText("Datos de un: Administrador");
                jTextCedula.setText(per.getCedula());
                jTextNombre.setText(per.getNombre());
                jTextApellido.setText(per.getApellido());
                jTextDireccion.setText(per.getDireccion());
                jTextConvencional.setText(per.getTelefonoConvencional());
                jTextCelular.setText(per.getTelefonoCelular());
                jTextUsuario.setText(per.getUsuario());
                jTextContraseña.setText(per.getContraseña());
                jTextCargo.setText(per.getCargo());
                
        }else if(per.getCargo().equalsIgnoreCase("E")){
            jTextCedula.setText(per.getCedula());
            jTextNombre.setText(per.getNombre());
            jTextApellido.setText(per.getApellido());
            jTextDireccion.setText(per.getDireccion());
                jTextConvencional.setText(per.getTelefonoConvencional());
                jTextCelular.setText(per.getTelefonoCelular());
                jTextUsuario.setText(per.getUsuario());
                jTextContraseña.setText(per.getContraseña());
                jTextCargo.setText(per.getCargo());
            datos.setText("Datos de un: Empledado");
        
        }
             } catch (Exception e) {
                  javax.swing.JOptionPane.showMessageDialog(null, "Empleado no Encontrado", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
         jTextCedula.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDireccion.setText("");
        jTextConvencional.setText("");
        jTextCelular.setText("");
        jTextCargo.setText("");
        jTextUsuario.setText("");
        jTextContraseña.setText("");
             }
             }
        
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if(jTextNombre.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Campo Nombre Vacio", "Error de Campos", javax.swing.JOptionPane.WARNING_MESSAGE);
          }else{
              Usuario per = new Usuario();
              jTextCedula.setText("");
                con.Conectar();
        per = controlPer.buscarEmpleadoDatos(con, jTextCedula.getText(), jTextNombre.getText());
        con.CerrarConexion();
        System.out.println("Datos : " +per);
        System.out.println("1");
              try {
                  id = per.getId();
                   if(per.getCargo().equalsIgnoreCase("C")){
        jTextCedula.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDireccion.setText("");
        jTextConvencional.setText("");
        jTextCelular.setText("");
        jTextCargo.setText("");
        jTextUsuario.setText("");
        jTextContraseña.setText("");
        info.setText("No se puede editar informacion");
        info2.setText("de un cliente en esta ventana");
            
        }else if(per.getCargo().equalsIgnoreCase("A")){
                datos.setText("Datos de un: Administrador");
                jTextCedula.setText(per.getCedula());
                jTextNombre.setText(per.getNombre());
                jTextApellido.setText(per.getApellido());
                jTextDireccion.setText(per.getDireccion());
                jTextConvencional.setText(per.getTelefonoConvencional());
                jTextCelular.setText(per.getTelefonoCelular());
                jTextUsuario.setText(per.getUsuario());
                jTextContraseña.setText(per.getContraseña());
                jTextCargo.setText(per.getCargo());
                
        }else if(per.getCargo().equalsIgnoreCase("E")){
            jTextCedula.setText(per.getCedula());
            jTextNombre.setText(per.getNombre());
            jTextApellido.setText(per.getApellido());
            jTextDireccion.setText(per.getDireccion());
                jTextConvencional.setText(per.getTelefonoConvencional());
                jTextCelular.setText(per.getTelefonoCelular());
                jTextUsuario.setText(per.getUsuario());
                jTextContraseña.setText(per.getContraseña());
                jTextCargo.setText(per.getCargo());
            datos.setText("Datos de un: Empledado");
        }
              } catch (Exception e) {
                  javax.swing.JOptionPane.showMessageDialog(null, "Empleado no Encontrado", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                  jTextCedula.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDireccion.setText("");
        jTextConvencional.setText("");
        jTextCelular.setText("");
        jTextCargo.setText("");
        jTextUsuario.setText("");
        jTextContraseña.setText("");
              }
          }
       
        System.out.println("sale");
        



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarDatosActionPerformed
         if(jTextNombre.getText().isEmpty() || jTextCedula.getText().isEmpty() || jTextApellido.getText().isEmpty()) {
             javax.swing.JOptionPane.showMessageDialog(null, "Nombre, Apellido, Cedula no pueden ser nulos", "Error de Campos", javax.swing.JOptionPane.WARNING_MESSAGE);
    
         }else{
             try {
                 con.Conectar();
        controlPer.actualizarDatosEmpleado(con, id, jTextCedula.getText(), jTextNombre.getText(),
                                                jTextApellido.getText(), jTextDireccion.getText(), 
                                                jTextConvencional.getText(), jTextCelular.getText(), jTextUsuario.getText(),
                                                jTextContraseña.getText(), jTextCargo.getText());
        con.CerrarConexion();
        javax.swing.JOptionPane.showMessageDialog(null, "Datos Actualizados", "Update", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        jTextCedula.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDireccion.setText("");
        jTextConvencional.setText("");
        jTextCelular.setText("");
        jTextCargo.setText("");
        jTextUsuario.setText("");
        jTextContraseña.setText("");
        
             } catch (Exception e) {
                 javax.swing.JOptionPane.showMessageDialog(null, "Verificar Longitud de: contraseña, Tel:convencional, Tel.Celular", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
             }
         }
        






    }//GEN-LAST:event_jButtonActualizarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datos;
    private javax.swing.JLabel info;
    private javax.swing.JLabel info2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizarDatos;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCargo;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextContraseña;
    private javax.swing.JTextField jTextConvencional;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
