/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.conexionDB;
import Controlador.ControlPersona;
import modelo.Usuario;

/**
 *
 * @author Macao
 */
public class eliminarEmpleado extends javax.swing.JFrame {

    
    Usuario user;
    ControlPersona controlPer ;
    conexionDB con = new conexionDB();
    int id;
    
    public eliminarEmpleado(Usuario usuario) {
        initComponents();
          user = usuario;
        controlPer = new ControlPersona();
        setLocationRelativeTo(null);
        setTitle("Eliminar un Empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datos = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        BuscarCedula = new javax.swing.JButton();
        BuscarNombre = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Cedula:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Nombre:");

        datos.setForeground(new java.awt.Color(0, 0, 255));
        datos.setText("Cargo:");

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Motivo de Eliminacion:");

        BuscarCedula.setText("Buscar por Cedula");
        BuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCedulaActionPerformed(evt);
            }
        });

        BuscarNombre.setText("Buscar por Nombre");
        BuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNombreActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextCedula)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BuscarCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(139, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresar)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarNombre))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Regresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCedulaActionPerformed
        if(jTextCedula.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Campo Cedula Vacio", "Error de Campos", javax.swing.JOptionPane.WARNING_MESSAGE);
    
         }else{
            Usuario per = new Usuario();
            jTextNombre.setText("");
            con.Conectar();
            per = controlPer.buscarEmpleadoDatos(con, jTextCedula.getText(), jTextNombre.getText());
            con.CerrarConexion();
             try {
                 id = per.getId();
                 if(per.getCargo().equalsIgnoreCase("C")){
                     javax.swing.JOptionPane.showMessageDialog(null, "Empleado no Encontrado", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                    
            
        }else if(per.getCargo().equalsIgnoreCase("A")){
                datos.setText("Cargo: Administrador");
                jTextCedula.setText(per.getCedula());
                jTextNombre.setText(per.getNombre());
                
        }else if(per.getCargo().equalsIgnoreCase("E")){
            datos.setText("Cargo: Empleado");
            jTextCedula.setText(per.getCedula());
            jTextNombre.setText(per.getNombre());
            
            
        }
             } catch (Exception e) {
                  javax.swing.JOptionPane.showMessageDialog(null, "Empleado no Encontrado", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                  
             }
             }
    }//GEN-LAST:event_BuscarCedulaActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void BuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNombreActionPerformed
        if(jTextNombre.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Campo Nombre Vacio", "Error de Campos", javax.swing.JOptionPane.WARNING_MESSAGE);
    
         }else{
            Usuario per = new Usuario();
            jTextCedula.setText("");
            con.Conectar();
            per = controlPer.buscarEmpleadoDatos(con, jTextCedula.getText(), jTextNombre.getText());
            con.CerrarConexion();
             try {
                 id = per.getId();
                 if(per.getCargo().equalsIgnoreCase("C")){
                     javax.swing.JOptionPane.showMessageDialog(null, "Empleado no Encontrado", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                    
            
        }else if(per.getCargo().equalsIgnoreCase("A")){
                datos.setText("Cargo: Administrador");
                jTextCedula.setText(per.getCedula());
                jTextNombre.setText(per.getNombre());
                
        }else if(per.getCargo().equalsIgnoreCase("E")){
            jTextCedula.setText("");
            jTextNombre.setText("");
            datos.setText("Cargo: Empleado");
            
        }
             } catch (Exception e) {
                  javax.swing.JOptionPane.showMessageDialog(null, "Empleado no Encontrado", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                  
             }
             }
        
        
        
        
        
        



    }//GEN-LAST:event_BuscarNombreActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
         if(jTextNombre.getText().isEmpty() || jTextCedula.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Campo Nombre o Cedula Vacio", "Error de Campos", javax.swing.JOptionPane.WARNING_MESSAGE);
    
         }else{
            con.Conectar();
            String estado = "I";
        controlPer.eliminarEmpleado(con, id, jTextCedula.getText(), jTextNombre.getText(), descripcion.getText(), estado);
        con.CerrarConexion();
        jTextCedula.setText("");
        jTextNombre.setText("");
        descripcion.setText("");
        datos.setText("Cargo:");
        javax.swing.JOptionPane.showMessageDialog(null, "Empleado Eliminado", "Exito", javax.swing.JOptionPane.WARNING_MESSAGE);
        
         }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        VntMenuEmpleado emm = new VntMenuEmpleado(user);
        emm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCedula;
    private javax.swing.JButton BuscarNombre;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel datos;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
